version: '3'

services:

    php:
        build:
            context: .
        volumes:
            - .:/var/www:rw
        environment:
            TZ: "Europe/Paris"
        links:
          - redis



    redis:
        image: redis:5.0-alpine
        ports:
          - 6379:6379
        environment:
            TZ: "Europe/Paris"